FROM debian:jessie

RUN apt-get update && \
    apt-get install -y libgmp-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/.cabal/bin
WORKDIR /root/.cabal/bin

COPY build/production.tar.gz /root/.cabal/bin/production.tar.gz
RUN tar -xzf production.tar.gz production

CMD ./production
